### ISSUE TITLE
Joan pull request #1

### ISSUE THREAD

**Issue by PaoloBiagini** [PaoloBiagini/Joan#2]
A couple of questions about path overlapping and file name updates listed in the pull request #1:

> - rename .glyphs file

Could we keep using the variant name (Joan-Regular.glyphs, Joan-Italic.glyphs ...)?

___

>However, the outlines could be improved, in some cases (screenshots), we have overlapping that could create conflicts at the export.
You can take a look to this: https://glyphsapp.com/learn/drawing-good-paths

The article says that is possible to keep intersections in the source, as long as the Remove Overlap option was activated in the Export dialog. Rather, I've noticed that this option is available for OTF/TTF formats only. Does this mean that conflicts could arise for webfonts?

<img width="500" alt="Screenshot 2021-12-11 at 16 22 59" src="https://user-images.githubusercontent.com/69169805/145687629-8ebfbd24-da49-4ef2-a0cf-725b5d407e4f.png">

**Comment by RosaWagner** [comment]
- First, we don't build fonts with Glyphs, we build them with Fontmake (it means that for example external open corners are still not yet allowed). Then, there is intersection and intersection, some are okay, other are creating rendering issues (overlaying segments is in general a bad idea).
- Binary file names (which have a mandatory scheme for GF Fonts) are created from the source file names and therefore should follow this scheme: FontName.glyphs and FontName-Italic.glyphs
